### PR TITLE
Feature: Add Redis SSL/TLS support

### PR DESCRIPTION
**Pull request by elartey**
Description:

As mentioned in the issue #444, `pgsync` currently does not support connecting to redis via SSL/TLS. This proves to be a challenge in environments where a SSL/TLS connection is required for Redis.

Todo:
- [x] Add unit tests
- [x] Update documentation

### CODE REVIEW

**Comment by elartey** [comment]
@toluaina please take a look at this when you can. I noticed there was some earlier work concerning enabling SSL/TLS in Redis but it was incomplete. This PR I believe will complete it. Let me know what you think.

P.S. Awesome work you're doing here 👏🏾

**Comment by johhud1** [comment]
Any reason this PR was closed and not merged? Are there any plans to implement this feature?

 Would be useful for me.  If there's any help I can provide, let me know.

**Comment by johhud1** [comment]
Ok , may have answered my own question.

To any future readers/googles. It seems this PR is about allowing pgsync to connect to redis via SSL with self-signed certs. However, if you're simply looking to connect to redis with a SSL/TLS secured connection with standard certs, you need only export `REDIS_SCHEME=rediss` before launching pgsync to enable that functionality.

**Comment by jmazella-brr** [comment]
For anyone having a problem with Redis/Valkey using self-signed certs, you can disable cert verification by specifying `REDIS_URL` instead of using `REDIS_SCHEME` `REDIS_HOST` and `REDIS_PORT`. The whole url needs the param `ssl_cert_reqs=none` to tell the lib to disable cert verification, example:

```
REDIS_URL=rediss://example.com:5432/0?ssl_cert_reqs=none
```
See [https://redis.readthedocs.io/en/stable/examples/ssl_connection_examples.html](https://redis.readthedocs.io/en/stable/examples/ssl_connection_examples.html)

Of course, its better to add the self-signed cert to the Python cert store if you can, be aware of the risks.

**Pull request closed without merging**
